name: Compile LESS to CSS (styles)

on:
  push:
    branches:
      - main
    paths:
      - 'styles.less'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install LESS
        run: npm install -g less

      - name: Compile LESS to CSS
        run: lessc styles.less styles.css

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          # Fetch and rebase
          git fetch origin main
          git checkout main
          git rebase origin/main

          git add styles.css
          if ! git diff --cached --quiet; then
            git commit -m "Compile styles.less to styles.css"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
          else
            echo "No changes to commit."
          fi
